CXXFLAGS += -O3 -std=c++14 -Isrc -I/usr/local//include
# CXXFLAGS += -O3 -std=c++14 -Isrc -I/src/tools/capnproto/c++/src -I/usr/local//include
	# -s USE_ZLIB=1  \
	# -s FORCE_FILESYSTEM=1  \
	# -s EXTRA_EXPORTED_RUNTIME_METHODS=["callMain"]  \
	# -s ALLOW_MEMORY_GROWTH=1  \
	 #-I@mathinc@ \
# CPPFLAGS += @amcppflags@

UNAME_S=$(shell uname -s)

ifeq ($(UNAME_S),Darwin)
	CXXFLAGS += -mmacosx-version-min=10.7 -stdlib=libc++
else
#	CXXFLAGS += -include src/mash/memcpyLink.h -Wl,--wrap=memcpy
#	CFLAGS += -include src/mash/memcpyLink.h
endif

SOURCES=\
	src/mash/Command.cpp \
	src/mash/CommandSize.cpp \
	src/mash/CommandList.cpp \
	src/mash/hash.cpp \
	src/mash/HashList.cpp \
	src/mash/HashPriorityQueue.cpp \
	src/mash/HashSet.cpp \
	src/mash/MinHashHeap.cpp \
	src/mash/MurmurHash3.cpp \
	src/mash/mash.cpp \
	src/mash/Size.cpp \
	src/mash/sizeParameterSetup.cpp \

OBJECTS=$(SOURCES:.cpp=.o) src/mash/capnp/MinHash.capnp.o

all : mash libmash.a

mash : libmash.a src/mash/memcpyWrap.o
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -o mash src/mash/memcpyWrap.o libmash.a /usr/local/lib/libcapnp.a /usr/local/lib/libkj.a -lz -lm
	#$(CXX) $(CXXFLAGS) $(CPPFLAGS) -o mash.html src/mash/memcpyWrap.o libmash.a /src/tools/capnproto/c++/.libs/libcapnp.a /src/tools/capnproto/c++/.libs/libkj.a -lz -lm -lworkerfs.js

libmash.a : $(OBJECTS)
	ar -cr libmash.a $(OBJECTS)
	ranlib libmash.a
	# emar -cr libmash.a $(OBJECTS)
	# emranlib libmash.a

.SUFFIXES :

%.o : %.cpp src/mash/capnp/MinHash.capnp.h
	$(CXX) -c $(CXXFLAGS) $(CPPFLAGS) -o $@ $<

%.o : %.c++
	$(CXX) -c $(CXXFLAGS) $(CPPFLAGS) -o $@ $<

src/mash/memcpyWrap.o : src/mash/memcpyWrap.c
	$(CC) $(CFLAGS) -c -o $@ $<

src/mash/capnp/MinHash.capnp.c++ src/mash/capnp/MinHash.capnp.h : src/mash/capnp/MinHash.capnp
	cd src/mash/capnp;export PATH=/usr/local/bin/:${PATH};capnp compile -I /usr/local/include -oc++ MinHash.capnp
	#cd src/mash/capnp;export PATH=/src/tools/capnproto/c++/.libs/:${PATH};capnp compile -I /src/tools/capnproto/c++/src -oc++ MinHash.capnp

install : mash
	mkdir -p /usr/local/bin/
	mkdir -p /usr/local/lib/
	mkdir -p /usr/local/include/
	mkdir -p /usr/local/include/mash
	mkdir -p /usr/local/include/mash/capnp
	cp `pwd`/mash /usr/local/bin/
	cp `pwd`/libmash.a /usr/local/lib/
	cp `pwd`/src/mash/*.h /usr/local/include/mash/
	cp `pwd`/src/mash/capnp/MinHash.capnp.h /usr/local/include/mash/capnp/

.PHONY: uninstall
uninstall:
	rm -f /usr/local/bin/mash
	rm -f /usr/local/lib/libmash.a
	rm -rf /usr/local/include/mash

clean :
	-rm mash
	-rm libmash.a
	-rm src/mash/*.o
	-rm src/mash/capnp/*.o
	-rm src/mash/capnp/*.c++
	-rm src/mash/capnp/*.h

.PHONY: test
test : testSketch testDist testScreen

testSketch : mash test/genomes.msh test/reads.msh
	./mash info -d test/genomes.msh > test/genomes.json
	./mash info -d test/reads.msh > test/reads.json
	diff test/genomes.json test/ref/genomes.json
	diff test/reads.json test/ref/reads.json

test/genomes.msh : mash
	cd test ; ../mash sketch -o genomes.msh genome1.fna genome2.fna genome3.fna

test/reads.msh : mash
	cd test ; ../mash sketch -r -I reads reads1.fastq reads2.fastq -o reads.msh

testDist : mash test/genomes.msh test/reads.msh
	./mash dist test/genomes.msh test/reads.msh > test/genomes.dist
	diff test/genomes.dist test/ref/genomes.dist

testScreen : mash test/genomes.msh
	cd test ; ../mash screen genomes.msh reads1.fastq reads2.fastq > screen
	diff test/screen test/ref/screen
